# Generated by Django 5.1.4 on 2025-03-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('image', models.ImageField(upload_to='upload/')),
                ('resume', models.ImageField(upload_to='upload/')),
            ],
        ),
    ]
