# Generated by Django 5.1.4 on 2025-03-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='resume',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
